### ISSUE TITLE
Accepted licenses

### ISSUE THREAD

**Issue by c00kiemon5ter** [IdentityPython/Governance#1]
We require an Apache2 license:

> ### [IdentityPython Projects][sec-idpy-proj]
> The software project must meet the following criteria:
> - Developed under an Apache2 license

and at the same time, we state we release everything under a copyleft license approved by FSF or OSI:

> ### [Licensing Policy][sec-idpy-lp]
> All software and content created or maintained within IdentityPython is to be made publicly available perpetually at no cost under one or more of the licenses on the Free Software Foundation's list of "recommended copyleft licenses" or any license approved by the Open Source Initiative on or after the submission date.

Should we relax the requirement to accept Apache2-only projects? or should we stick to it and rephrase the licensing policy?

  [sec-idpy-proj]: https://github.com/IdentityPython/Governance/blob/master/DRAFT-idpy-statutes.md#identitypython-projects
  [sec-idpy-lp]: https://github.com/IdentityPython/Governance/blob/master/DRAFT-idpy-statutes.md#licensing-policy

**Comment by hlflanagan** [comment]
Keep in mind we already have a mix of 2-clause BSD and Apache. So, perhaps rephrase to Apache going forward, grandfathering in the BSD stuff (since it sounded unlikely that SUNET or NORDUnet was willing to change it)?

**Comment by c00kiemon5ter** [comment]
Good suggestion. I moved forward with it and rephrased the requirement.
